title = "Olivine"
description = "A theme for a personal knowledge base"
base_url = "https://dongryul-kim.github.io/olivine"

compile_sass = true
#generate_feed = true
taxonomies = [ { name = "tags" } ]
build_search_index = true

[markdown]
highlight_code = true
external_links_target_blank = true
smart_punctuation = true

[link_checker]
internal_level = "warn"

[search]
index_format = "elasticlunr_json"

# The following are the default values
[extra.olivine]
journal = true   # Enables journal functionality
calendar = true  # Enables calendar view in default page
mathjax = true   # Enables MathJax
graph = true     # Enables graph view
extra_js = [ ]   # Extra javascript files, an array of strings


