name = "Olivine"
description = "A Zola theme for a personal knowledge base"
license = "MIT"
homepage = "https://github.com/dongryul-kim/olivine"
min_version = "0.17.2"
demo = "https://dongryul-kim.github.io/olivine/"

[extra.olivine]
journal = true
calendar = true
search = true
graph = true
mathjax = true
extra_js = [ ]

[author]
name = "Dongryul Kim"
homepage = "https://web.stanford.edu/~dkim04/"
